### ISSUE TITLE
Performance benchamarks 

### ISSUE THREAD

**Issue by gkorland** [Diggsey/ijson#7]
Did you run performance benchmarks? 

E.g.
https://github.com/serde-rs/json-benchmark

**Comment by Diggsey** [comment]
This crate does not implement the serialization logic (ie. the `Serializer`/`Deserializer` traits) - it relies on `serde-json` or other crate for that. It only implements types that implement `Serialize`/`Deserialize`.

**Comment by gkorland** [comment]
These are the results we got running the benchmark, it indeed seems very similar to serde_json results.
```
                                DOM                  STRUCT
======= serde_json ======= parse|stringify ===== parse|stringify ====
data/canada.json         310 MB/s   460 MB/s   450 MB/s   360 MB/s
data/citm_catalog.json   340 MB/s   620 MB/s   740 MB/s   990 MB/s
data/twitter.json        290 MB/s  1020 MB/s   580 MB/s  1230 MB/s

========= ijson ========== parse|stringify ===== parse|stringify ====
data/canada.json         230 MB/s   410 MB/s   450 MB/s   370 MB/s
data/citm_catalog.json   310 MB/s   640 MB/s   740 MB/s   990 MB/s
data/twitter.json        190 MB/s   960 MB/s   570 MB/s  1230 MB/s
```

**Comment by gkorland** [comment]
@Diggsey do you think it will be easy to use [simd-json](https://crates.io/crates/simd-json) for parsing in combined with ijson?

**Comment by Diggsey** [comment]
Any `serde`-compatible serializer should work out of the box with `ijson`.

**Comment by gkorland** [comment]
:+1:
